export enum ActionTypes {
  // Admin
  GET_PRODUCT_ORDER_LIST = 'GET_PRODUCT_ORDER_LIST',

  // Design Technician
  SHOW_NOTIFICATION = 'SHOW_NOTIFICATION',
  GET_SOFTBILL_DATA = 'GET_SOFTBILL_DATA',
  UPDATE_SOFTBILL_DATA = 'UPDATE_SOFTBILL_DATA',
  UPDATE_SELECTED_SOFTBILL_DATA = 'UPDATE_SELECTED_SOFTBILL_DATA',
  GET_PICTURELIST_NEW = 'GET_PICTURELIST_NEW',
  UPDATE_PICTURE_LIST_NEW = 'UPDATE_PICTURE_LIST_NEW',
  UPDATE_SELECTED_PICTURE_LIST_ITEM_NEW = 'UPDATE_SELECTED_PICTURE_LIST_ITEM_NEW',
  GET_DEFAULT_PLANT_NUMBER = 'GET_DEFAULT_PLANT_NUMBER',
  GET_PLANT_NUMBER_LIST = 'GET_PLANT_NUMBER_LIST',
  GET_USER_DETAILS = 'GET_USER_DETAILS',
  GET_WORKORDER_DETAILS = 'GET_WORKORDER_DETAILS',
  UPDATE_PICTURE_LIST = 'UPDATE_PICTURE_LIST',
  UPDATE_SELECTED_PICTURE_LIST_ITEM = 'UPDATE_SELECTED_PICTURE_LIST_ITEM',

  // Admin
  GET_RAISE_FLAG_SEARCH_LIST = 'GET_RAISE_FLAG_SEARCH_LIST',
  UPDATE_SEARCH_LIST = 'UPDATE_SEARCH_LIST',
  ADD_RAISE_FLAG = 'ADD_RAISE_FLAG',
}
